### ISSUE TITLE
Creating new droplet defaults to invalid parameters

### ISSUE THREAD

**Issue by benjamincohen1** [ahmontero/dop#20]
The default parameters for creating new droplets are -1s, which will provide an error.  The error gives no hint that this is the issue.  I think that either the error should be more verbose that there are invalid parameters, or the default parameters should be legal values instead of -1.

**Comment by ahmontero** [comment]
I will work on it. In fact, I will improve some aspects of the code that I do not like too much...

**Comment by ahmontero** [comment]
I have just released new beta version 1.6.b1 with better support for Digital Ocean api.

**Comment by zero-master** [comment]
I don't see POST method in Digital Ocean API docs. Why are you using POST to reboot, resize, snapshot ?

**Comment by ahmontero** [comment]
You are so right. It was a bug. Fixed now.

**Comment by Eriksh** [comment]
Quick question,

I'm fairly new to python, so I apologize for sounding a little stupid
but how do you create a droplet?

I've been trying to pass values to the function but I'm guessing that
not how it works :(

If you could also post an example on the README document 
it would help anyone else who has the same issue.

**Comment by ahmontero** [comment]
Hi Eriksh,

I have created a new issue with those improvements. You can follow it here: https://github.com/ahmontero/dop/issues/22

Regards
