### ISSUE TITLE
Improve examples of use

### ISSUE THREAD

**Issue by ahmontero** [ahmontero/dop#22]
Improve examples of use. Add some code to README

**Comment by Eriksh** [comment]
Thx for taking your time to update the manual,
it will go a long way to helping noobs like me.

However, I'm currently in a position where I am doing
a task for HighTech Edventure organization.  Is it possible
you can post an example on how you create a droplet here?

Would be appreciated :)

**Comment by ahmontero** [comment]
Now there is a little more info in the readme plus I fixed a bug.

**Comment by Eriksh** [comment]
Greatly appreciated!

Thank you for making this great API!
